### ISSUE TITLE
Having the spells in a separate repository.

### ISSUE THREAD

**Issue by saltukalakus** [auth0-extensions/auth0-reset-tenant#27] opened 2016-12-25 13:37 UTC
Spells could be moved to another repository. This will enhance the decoupling between spells and the wizard. ( auth0-spells for example. )

**Comment by twistedstream** [comment] 2016-12-27 15:23
+1

This is a duplicate of #10, but lets keep this one since it's following our new terminology

**Comment by saltukalakus** [comment] 2016-12-27 17:11
Oops sorry.

**Closed as completed** 2018-11-16 17:49 UTC
Labels: enhancement, wontfix
